//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficialCPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int MonitorId { get; set; }
        public int TicketNumber { get; set; }
        public Nullable<System.DateTime> TimeLeft { get; set; }
        public Nullable<System.DateTime> ReturnTime { get; set; }
        public string Parkedby { get; set; }
        public Nullable<System.DateTime> TimeRequested { get; set; }
        public string Deliverer { get; set; }
        public Nullable<int> ReparkedLocat { get; set; }
    
        public virtual OwnersInformation OwnersInformation { get; set; }
        public virtual Driver DeriveryDriver { get; set; }
        public virtual Driver Parker { get; set; }
    }
}
